######################################################################
# Automatically generated by qmake (2.01a) Sat May 4 15:37:23 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

#CONFIG += console qtestlib

QT += network testlib

# Input
HEADERS += sheer_cloud.h test.h
SOURCES += sheer_cloud.cpp test.cpp
