######################################################################
# Automatically generated by qmake (2.01a) Fri May 3 06:30:34 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sheer_cloud.h
SOURCES += sheer_cloud.cpp test.cpp
